Repository miniyom/RED_CYPHER_Project, pull requests merged in 2023-08, with the labels that each got.

#3 DB 데이터 설정파일 이동, vuejs Controller 별도 추가
  .gitignore
  src/main/java/com/cyphers/game/RecordSearch/config/DatabaseConfig.java
  src/main/java/com/cyphers/game/RecordSearch/controller/VueController.java
  src/main/resources/application.properties
Labels: enhancement

#4 vuejs 2 버전으로 migration, User CRUD용 페이지 생성
  cyphers-record-search/.gitignore
  cyphers-record-search/README.md
  cyphers-record-search/babel.config.js
  cyphers-record-search/jsconfig.json
  cyphers-record-search/package-lock.json
  cyphers-record-search/package.json
  cyphers-record-search/public/favicon.ico
  cyphers-record-search/public/index.html
  cyphers-record-search/src/App.vue
  cyphers-record-search/src/assets/logo.png
  cyphers-record-search/src/components/HelloWorld.vue
  cyphers-record-search/src/main.js
  cyphers-record-search/src/router/router.js
  cyphers-record-search/src/views/UserEdit.vue
  cyphers-record-search/src/views/UserList.vue
  cyphers-record-search/vue.config.js
  src/main/java/com/cyphers/game/RecordSearch/controller/UserController.java
  src/main/java/com/cyphers/game/RecordSearch/controller/VueController.java
  src/main/resources/application.properties
  src/main/resources/datasource.properties
  src/main/resources/static/css/app.6fbb0451.css
  src/main/resources/static/css/app.b2d625b8.css
  src/main/resources/static/css/chunk-vendors.a38d9a19.css
  src/main/resources/static/index.html
  src/main/resources/static/js/app.11601784.js
  src/main/resources/static/js/app.11601784.js.map
  src/main/resources/static/js/app.25359c32.js
  src/main/resources/static/js/app.25359c32.js.map
  src/main/resources/static/js/app.6141c8c8.js
  src/main/resources/static/js/app.6141c8c8.js.map
  src/main/resources/static/js/app.830526d5.js
  src/main/resources/static/js/app.830526d5.js.map
  src/main/resources/static/js/app.f8192b02.js
  src/main/resources/static/js/app.f8192b02.js.map
  src/main/resources/static/js/chunk-vendors.a99d5180.js
  src/main/resources/static/js/chunk-vendors.a99d5180.js.map
Labels: enhancement

#6 OpenApi 붙이기 - 플레이어 정보조회
  src/main/java/com/cyphers/game/RecordSearch/cyphers/OpenApi_MatchingHistory.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/OpenApi_PlayerInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersMatchingHistory.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersPlayerInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersPlayerRecords.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersRecords.java
Labels: documentation

#8 openapi 리팩토링 작업
  cyphers-record-search/test2/favicon.ico
  cyphers-record-search/test2/index.html
  src/main/java/com/cyphers/game/RecordSearch/controller/UserController.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/CyphersApiService.java
Labels: enhancement

#9 충돌실험
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersCharacterAttribute.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersCharacterPosition.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersMapInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersMatches.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersMatchingHistory.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersMathedInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersPartyInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersPlayDate.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersPlayInfo.java
Labels: enhancement

#10 Minhyeok/230814/create models
  src/main/java/com/cyphers/game/RecordSearch/cyphers/CyphersApiService.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersCharacterInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersCharacterRankInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersCharacterRanking.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersCharacterSearch.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersEquipItems.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersItemDetailInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersItemInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersItemMultiDetailSearch.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersItemSearch.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersMatchingDetails.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersPlayerRankInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersPlayerRanking.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersPlayersInGame.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersPositionAttribute.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersTeamInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersTsjRankInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersTsjRanking.java
Labels: enhancement

#15 검색 상세페이지 디자인 추가
  cyphers-record-search/package-lock.json
  cyphers-record-search/package.json
  cyphers-record-search/src/components/BarGraph.vue
  cyphers-record-search/src/components/LineGraph.vue
  cyphers-record-search/src/router/router.js
  cyphers-record-search/src/views/cyphers/RecordDetailView.vue
Labels: enhancement

#16 Swagger 라이브러리 적용
  pom.xml
  src/main/java/com/cyphers/game/RecordSearch/controller/user/UserController.java
  src/main/resources/application.properties
  src/test/java/com/cyphers/game/RecordSearch/controller/UserControllerTest.java
Labels: documentation

#18 검색창 입력 값 비동기 통신으로 자동완성 리스트 구현 완료
  cyphers-record-search/src/views/cyphers/MainView.vue
  pom.xml
  src/main/java/com/cyphers/game/RecordSearch/controller/search/SearchController.java
  src/main/java/com/cyphers/game/RecordSearch/controller/user/UserController.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/CyphersApiService.java
  src/main/java/com/cyphers/game/RecordSearch/service/SearchService.java
Labels: enhancement

#19 상세페이지 Response 설계
  cyphers-record-search/src/components/LineGraph.vue
  cyphers-record-search/src/components/PieGraph.vue
  cyphers-record-search/src/views/UserList.vue
  cyphers-record-search/src/views/cyphers/MainView.vue
  cyphers-record-search/src/views/cyphers/RecordDetailView.vue
  cyphers-record-search/src/views/cyphers/tanker.png
  src/main/java/com/cyphers/game/RecordSearch/Utils/CrsObjectMapper.java
  src/main/java/com/cyphers/game/RecordSearch/controller/search/SearchController.java
  src/main/java/com/cyphers/game/RecordSearch/controller/search/model/IoSearchDetailGameRecord.java
  src/main/java/com/cyphers/game/RecordSearch/controller/search/model/IoSearchDetailMostCypherInfo.java
  src/main/java/com/cyphers/game/RecordSearch/controller/search/model/IoSearchDetailRatingPointHistoryInfo.java
  src/main/java/com/cyphers/game/RecordSearch/controller/search/model/IoSearchDetailRecentlyPlayCyphersInfo.java
  src/main/java/com/cyphers/game/RecordSearch/controller/search/model/IoSearchDetailResponse.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/OpenApi_PlayerInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/CyphersPlayInfo.java
  src/main/java/com/cyphers/game/RecordSearch/cyphers/model/enumuration/CyphersGameType.java
  src/main/java/com/cyphers/game/RecordSearch/service/SearchService.java
Labels: enhancement

#20 try catch 삭제
  src/main/java/com/cyphers/game/RecordSearch/service/SearchService.java
Labels: bug

#22 PieGraph 비율조정 및 상세 속성 수정 디자인작업 추가
  cyphers-record-search/public/img/ad.png
  cyphers-record-search/public/img/assassin.png
  cyphers-record-search/public/img/supporter.png
  cyphers-record-search/public/img/tanker.png
  cyphers-record-search/src/components/PieGraph.vue
  cyphers-record-search/src/views/cyphers/RecordDetailView.vue
  cyphers-record-search/src/views/cyphers/tanker.png
  src/main/resources/static/css/app.1831e633.css
  src/main/resources/static/css/app.49406d22.css
  src/main/resources/static/img/ad.png
  src/main/resources/static/img/assassin.png
  src/main/resources/static/img/supporter.png
  src/main/resources/static/img/tanker.png
  src/main/resources/static/index.html
  src/main/resources/static/js/app.63f72dda.js
  src/main/resources/static/js/app.63f72dda.js.map
  src/main/resources/static/js/app.d08da735.js
  src/main/resources/static/js/app.d08da735.js.map
  src/main/resources/static/js/chunk-vendors.a99d5180.js
  src/main/resources/static/js/chunk-vendors.a99d5180.js.map
  src/main/resources/static/js/chunk-vendors.f4390eb1.js
Labels: enhancement
